[package]
name = "lean-for-the-inept-mathematician"
version = "0.1.0"
lean_version = "leanprover-community/lean:3.42.0"
path = "lean"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "2b92d080bb7c7c69e0e357b73a1ecd1fc5035217"}
