[package]
name = "lean-for-the-inept-mathematician"
version = "0.1.0"
lean_version = "leanprover-community/lean:3.43.0"
path = "lean"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "7ee73e4af4d0e8cfb5d2b871e911dd8aa29c8479"}
