[package]
name = "lean-for-the-inept-mathematician"
version = "0.1.0"
lean_version = "leanprover-community/lean:3.41.0"
path = "lean"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "d04fff95f686d5c372f7895551c40e7fa683ed6b"}
