[package]
name = "lean-for-the-inept-mathematician"
version = "0.1.0"
lean_version = "leanprover-community/lean:3.39.2"
path = "lean"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "6298a431db36e71ed76d6b6b421c4cec91ead16b"}
