[package]
name = "lean-for-the-inept-mathematician"
version = "0.1.0"
lean_version = "leanprover-community/lean:3.42.1"
path = "lean"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "fc3de1972fd9f6f215b9d3910a093b3dec92fc51"}
